<?php
// 配置不同角色拥有的权限
return [
	// admin后台
	'admin'       => [
		'operate.home'                        => true, //运营首页
		'operate.users'                       => true,
		'operate.gold_logs'                   => true,
		'operate.game_logs'                   => true,
		'operate.gold_adjustment'             => true,
		'operate.bank_gold_adjustment'        => true,
		'operate.account_blocking'            => true,
		'operate.game_message'                => true,
		'operate.update_game_message'         => true,
		'operate.game_tax'                    => true,
		'operate.users_online'                => true,
		'operate.report_logs'                 => true,
		'operate.exchange_orders'             => true,
		'operate.exchange_setting'            => true,
		'operate.update_service_list'         => true,
		'operate.service_list'                => true,
		'operate.register_setting'            => true,
		'operate.report_setting'              => true,
		'operate.login_logs'                  => true,
		'operate.operate_logs'                => true,
		'operate.charge_orders'               => true,
		'operate.update_exchange_setting'     => true,
		'operate.update_register_setting'     => true,
		'operate.update_report_setting'       => true,
		'operate.game_room_setting'           => true,
		'operate.update_game_room_setting'    => true,
		'operate.update_game_room_status'     => true,
		'operate.robot_setting'               => true,
		'operate.update_robot_setting'        => true,
		'operate.update_gold'                 => true,
		'operate.update_bank_gold'            => true,
		'operate.update_account'              => true,
		'operate.update_account_state'        => true,
		'operate.insert_message'              => true,
		'operate.insert_sys_message'          => true,
		'operate.delete_message'              => true,
		'operate.yrbw_setting'                => true,
		'operate.update_yrbw_setting'         => true,
		'operate.insert_yrbw_setting_respond' => true,
		'operate.delete_yrbw_setting_respond' => true,
		'operate.gm_account_list'             => true,
		'operate.insert_gm_account'           => true,
		'operate.update_gm_account'           => true,
		'operate.delete_gm_account'           => true,
		'operate.update_exchange'             => true,
		'operate.exchange_channel'            => true,
		'operate.update_exchange_channel'     => true,
		'operate.recharge_channel'            => true,
		'operate.update_recharge_channel'     => true,
		'agent.promo_statics'                 => true,
		'agent.agent_list'                    => true,
		'agent.promo_list'                    => true,
		'agent.settle_record'                 => true,
		'agent.promo_url'                     => true,
		'agent.account'                       => true,
		'agent.transfer_record'               => true,
		'agent.merchant_setting'              => true,
		'agent.agent_message'                 => true,
		'agent.buy_record'                    => true,
		'agent.income_list'                   => true,
		'agent.income_detail_list'            => true,
		// 'agent.insert_transfer'=>true,// 代理转账 (转账操作)
		'agent.update_settlement'             => true,
		// 'agent.insert_settlement'=>true, // 提交结算
		'agent.insert_merchant_setting'       => true,
		'agent.update_merchant_setting'       => true,
		'agent.delete_merchant_setting'       => true,
		'agent.insert_agent_message'          => true,
		'agent.update_agent_message'          => true,
		'agent.delete_agent_message'          => true,
		'agent.insert_agent_account'          => true,
		'agent.update_agent_account'          => true,  //修改代理
		'agent.update_agent_account_settle'   => true,//  结算账户，结算密码
		'agent.delete_agent_account'          => true,
		'agent.recharge_setting'              => true,
		'agent.update_recharge_setting'       => true,
		'agent.potato_robot_statics'          => true,
		'agent.user_win_total'                => true,
		'agent.user_charge_total'             => true,
		'operate.tax_statics'                 => true,//税收统计
		'operate.ol_statics'                  => true,//在线统计
		'operate.withdraw_statics'            => true,//提现统计
		'operate.charge_statics'              => true,//充值统计
		'agent.api_log_list'                  => true,//api接口日志接口
		'admin.api_to_request'                => true,
		'agent.ag_update_my_item'             => true,
		'agent.ag_get_my_item'                => true,
		'agent.ag_get_item_record_list'       => true,
		'agent.ag_get_shop_list'              => true,
		'agent.ag_update_shop_list'           => true,
		'agent.ag_delete_shop_list'           => true,
		'admin.risk_management'               => true,
		'admin.risk_management_update'        => true,
		'admin.risk_record'                   => true,
		'admin.no_read_risk_record'           => true,
		'admin.risk_record_update'            => true,
		'admin.risk_records_update'           => true,
		'admin.reset_google_captcha'          => true,
		'chat.player_summary'                 => true,
		'agent.ag_get_promo_setting'          => true,
		'agent.ag_update_promo_setting'       => true,
		'agent.ag_get_game_win_total'         => true,
        'agent.ag_get_award_setting'          => true,
        'agent.ag_update_award_setting'       => true,
        'agent.ag_gold_detail'                => true,
        'agent.ag_gold_source'                => true,
        'agent.ag_get_red_packet_setting'     => true,
        'agent.ag_update_red_packet_setting'  => true,
        'agent.ag_insert_red_packet'          => true,
        'agent.ag_insert_user_message'        => true,
        'agent.ag_get_ranklist_setting'       => true,
        'agent.ag_update_ranklist_setting'    => true,
        'agent.ag_get_red_packet_list'        => true,
        'agent.ag_sys_red_packet'             => true,
        'agent.ag_rank_user_list'             => true,
        'agent.ag_get_filter'                 => true,
        'agent.ag_insert_filter'              => true,
        'agent.ag_update_filter'              => true,
        'agent.ag_get_LimitUser'              => true,
        'agent.ag_insert_LimitUser'           => true,
        'agent.ag_update_LimitUser'           => true,
        'agent.ag_get_player_transfer_record' => true,
        'agent.ag_update_player_transfer_record' => true,
        'agent.ag_get_agent_transfer_record' => true,
        'agent.ag_get_agent_packages'         => true,
        'agent.ag_update_agent_packages'      => true,
        'agent.ag_get_wj_static'              => true,
        'agent.ag_get_player_footmark'        => true,
        'agent.ag_get_new_player_list'        => true,
        'agent.api_get_record_list'           => true,
        'agent.api_get_account'               => true,
        'agent.api_update_account'            => true,
        'agent.api_insert_account'            => true,
        'withdrawal.all-list'                 => true,
        'withdrawal.stat-list'                => true,
	],
	// 运营
	'operate'     => [
		'operate.home'                        => true, //运营首页
		'operate.users'                       => true, // 用户查询
		'operate.gold_logs'                   => true,//金币查询
		'operate.game_logs'                   => true,//游戏日志
		'operate.gold_adjustment'             => true,
		'operate.bank_gold_adjustment'        => true,
		'operate.account_blocking'            => true,
		'operate.game_message'                => true,//游戏公告
		'operate.update_game_message'         => true,
		'operate.game_tax'                    => true,//游戏税收
		'operate.users_online'                => true,//在线玩家
		'operate.report_logs'                 => true,
		'operate.exchange_orders'             => true,//提现订单
		'operate.exchange_setting'            => true,
		'operate.update_service_list'         => true,
		'operate.service_list'                => true,
		'operate.register_setting'            => true,
		'operate.report_setting'              => true,
		'operate.login_logs'                  => true,
		'operate.operate_logs'                => true,
		'operate.charge_orders'               => true,//充值订单
		'operate.update_exchange_setting'     => true,
		'operate.update_register_setting'     => true,
		'operate.update_report_setting'       => true,
		'operate.game_room_setting'           => true,
		'operate.update_game_room_setting'    => true,
		'operate.update_gold'                 => true,
		'operate.update_bank_gold'            => true,
		'operate.update_account'              => true,
		'operate.insert_message'              => true,
		'operate.insert_sys_message'          => true,
		'operate.delete_message'              => true,
		'operate.yrbw_setting'                => true,
		'operate.update_yrbw_setting'         => true,
		'operate.insert_yrbw_setting_respond' => true,
		'operate.delete_yrbw_setting_respond' => true,
		'operate.gm_account_list'             => true,
		'operate.insert_gm_account'           => true,
		'operate.update_gm_account'           => true,//账户设置（修改自己账户的密码和昵称
		'operate.delete_gm_account'           => true,
		'operate.update_exchange'             => true,
		'operate.exchange_channel'            => true,
		'operate.update_exchange_channel'     => true,
		'operate.recharge_channel'            => true,
		'operate.update_recharge_channel'     => true,
		'agent.promo_statics'                 => true,
		'agent.agent_list'                    => true,
		'agent.promo_list'                    => true,
		'agent.settle_record'                 => true,
		'agent.promo_url'                     => true,
		'agent.account'                       => true,
		'agent.transfer_record'               => true,
		'agent.merchant_setting'              => true,
		'agent.agent_message'                 => true,
		'agent.buy_record'                    => true,
		'agent.income_list'                   => true,
		'agent.income_detail_list'            => true,
		'agent.insert_transfer'               => true,
//		'agent.update_settlement'             => true,
		// 'agent.insert_settlement'=>true, // 代理申请提现 (提交结算)
		'agent.insert_merchant_setting'       => true,
		'agent.update_merchant_setting'       => true,
		'agent.delete_merchant_setting'       => true,
		'agent.insert_agent_message'          => true,
		'agent.update_agent_message'          => true,
		'agent.delete_agent_message'          => true,
		'agent.insert_agent_account'          => true,
		'agent.update_agent_account'          => true,//修改代理账号 (结算账户，结算密码)
		'agent.delete_agent_account'          => true,
		'agent.recharge_setting'              => true,
		'agent.update_recharge_setting'       => true,
		'agent.potato_robot_statics'          => true, // 数据报表 -统计
		'agent.user_win_total'                => true, // 数据报表 -用户输赢
		'agent.user_charge_total'             => true, // 数据报表 -用户充值
		'operate.tax_statics'                 => true,//税收统计
		'operate.ol_statics'                  => true,//在线统计
		'operate.withdraw_statics'            => true,//提现统计
		'operate.charge_statics'              => true,//充值统计
        'chat.player_summary'                 => true,
        'agent.ag_get_game_win_total'         => true,
        'agent.ag_gold_source'                => true,
        'agent.ag_get_ranklist_setting'       => true,
        'agent.ag_update_ranklist_setting'    => true,
        'agent.ag_get_red_packet_list'        => true,
        'agent.ag_sys_red_packet'             => true,
        'agent.ag_rank_user_list'             => true,
        'agent.update_agent_account_settle' => true,//  结算账户，结算密码
        'agent.ag_game_custom_setting'        => true,
        'agent.ag_game_info'                  => true,
        'agent.ag_get_player_transfer_record' => true,
        'agent.ag_get_agent_transfer_record' => true,
        'agent.ag_get_wj_static' => true,
        'agent.ag_get_player_footmark' => true,
        'agent.ag_get_new_player_list' => true,

    ],
	// 客服 主管客服
	'service999'  => [
		// 'operate.home'                        => true, //运营首页
		'operate.users'             => true, // 用户查询
		'operate.gold_logs'         => true,//金币查询
		'operate.game_logs'         => true,//游戏日志
		// 'operate.gold_adjustment'             => true,
		// 'operate.account_blocking'            => true,
		// 'operate.game_message'                => true,//游戏公告
		// 'operate.update_game_message'         => true,
		// 'operate.game_tax'                    => true,//游戏税收
		// 'operate.users_online'                => true,//在线玩家
		'operate.report_logs'       => true,//举报记录
		'operate.exchange_orders'   => true,//提现订单
		// 'operate.exchange_setting'            => true,
		// 'operate.update_service_list'         => true,
		'operate.service_list'      => true,//客服反馈
		// 'operate.register_setting'            => true,
		// 'operate.report_setting'              => true,
		// 'operate.login_logs'                  => true,
		// 'operate.operate_logs'                => true,
		'operate.charge_orders'     => true,//充值订单
		// 'operate.update_exchange_setting'     => true,
		// 'operate.update_register_setting'     => true,
		// 'operate.update_report_setting'       => true,
		// 'operate.game_room_setting'           => true,
		// 'operate.update_game_room_setting'    => true,
		// 'operate.update_gold'                 => true,
		// 'operate.update_bank_gold'            => true,
		// 'operate.update_account'              => true,
		// 'operate.insert_message'              => true,
		// 'operate.insert_sys_message'          => true,
		// 'operate.delete_message'              => true,
		// 'operate.yrbw_setting'                => true,
		// 'operate.update_yrbw_setting'         => true,
		// 'operate.insert_yrbw_setting_respond' => true,
		// 'operate.delete_yrbw_setting_respond' => true,
		// 'operate.gm_account_list'             => true,
		// 'operate.insert_gm_account'           => true,
		'operate.update_gm_account' => true,//账户设置（修改自己账户的密码和昵称
		// 'operate.delete_gm_account'           => true,
		// 'operate.update_exchange'             => true,//提现审核（玩家提现审核）
		// 'operate.exchange_channel'            => true,
		// 'operate.update_exchange_channel'     => true,
		// 'operate.recharge_channel'            => true,
		// 'operate.update_recharge_channel'     => true,
		// 'agent.promo_statics'                 => true,
		// 'agent.agent_list'                    => true,
		// 'agent.promo_list'                    => true,
		// 'agent.settle_record'                 => true,
		// 'agent.promo_url'                     => true,
		// 'agent.account'                       => true,
		// 'agent.transfer_record'               => true,
		// 'agent.merchant_setting'              => true,
		// 'agent.agent_message'                 => true,
		// 'agent.buy_record'                    => true,
		// 'agent.income_list'                   => true,
		// 'agent.income_detail_list'            => true,
		// 'agent.insert_transfer'               => true,
		// 'agent.update_settlement'             => true,
		// 'agent.insert_settlement'=>true, // 代理申请提现 (提交结算)
		// 'agent.insert_merchant_setting'       => true,
		// 'agent.update_merchant_setting'       => true,
		// 'agent.delete_merchant_setting'       => true,
		// 'agent.insert_agent_message'          => true,
		// 'agent.update_agent_message'          => true,
		// 'agent.delete_agent_message'          => true,
		// 'agent.insert_agent_account'          => true,
		// 'agent.update_agent_account'          => true,//修改代理账号 (结算账户，结算密码)
		// 'agent.delete_agent_account'          => true,
		// 'agent.recharge_setting'              => true,
		// 'agent.update_recharge_setting'       => true,
		// 'agent.potato_robot_statics'          => true, // 数据报表 -统计
		// 'agent.user_win_total'                => true, // 数据报表 -用户输赢
		// 'agent.user_charge_total'             => true, // 数据报表 -用户充值
		// 'operate.tax_statics'                 => true,//税收统计
		// 'operate.ol_statics'                  => true,//在线统计
		'operate.withdraw_statics'  => true,//提现统计
		'operate.charge_statics'    => true,//充值统计
		'chat.player_summary'       => true,
        'agent.ag_gold_source'                => true,
        'agent.ag_get_player_transfer_record' => true,
        'agent.ag_get_player_footmark' => true,
        'agent.ag_get_new_player_list' => true,

    ],
	// 客服 普通客服
	'service100'  => [
		'operate.users'               => true, // 用户查询
		'operate.gold_logs'           => true,//金币查询
		'operate.game_logs'           => true,//游戏日志
		'operate.report_logs'         => true,//举报记录
		'operate.exchange_orders'     => true,//提现订单
		'operate.service_list'        => true,//客服反馈列表
		'operate.update_service_list' => true,//客服反馈回复
		'operate.charge_orders'       => true,//充值订单
		'operate.update_gm_account'   => true,//账户设置（修改自己账户的密码和昵称
		// 'operate.update_exchange'             => true,//提现审核（玩家提现审核）
		// 'operate.tax_statics'                 => true,//税收统计
		// 'operate.ol_statics'                  => true,//在线统计
		'operate.withdraw_statics'    => true,//提现统计
		'operate.charge_statics'      => true,//充值统计
		'chat.player_summary'         => true,
        'agent.ag_gold_source'        => true,
        'agent.ag_get_player_transfer_record' => true,
        'agent.ag_get_player_footmark' => true,
        'agent.ag_get_new_player_list' => true,

    ],
	// 客服 审核客服
	'service1000' => [
		'operate.users'             => true, // 用户查询
		'operate.gold_logs'         => true,//金币查询
		'operate.game_logs'         => true,//游戏日志
		// 'operate.report_logs'                 => true,//举报记录
		'operate.exchange_orders'   => true,//提现订单
		// 'operate.service_list'                => true,//客服反馈
		'operate.charge_orders'     => true,//充值订单
		'operate.update_gm_account' => true,//账户设置（修改自己账户的密码和昵称
		'operate.update_exchange'   => true,//提现审核（玩家提现审核）
		// 'operate.tax_statics'                 => true,//税收统计
		// 'operate.ol_statics'                  => true,//在线统计
		'operate.withdraw_statics'  => true,//提现统计
		'operate.charge_statics'    => true,//充值统计
		'chat.player_summary'       => true,
        'agent.ag_gold_source'      => true,
        'agent.ag_get_player_transfer_record' => true,
        'agent.ag_update_player_transfer_record' => true,
        'agent.ag_get_player_footmark' => true,
        'agent.ag_get_new_player_list' => true,
    ],
	'agent'       => [
        'operate.users'               => true, // 用户查询
        'operate.game_logs'           => true,//游戏日志

        'agent.promo_statics'               => true,//代理首页
		'agent.agent_list'                  => true,//代理管理
		'agent.promo_list'                  => true,//代理推广统计
		'agent.settle_record'               => true,
		'agent.promo_url'                   => true,//推广地址
		'agent.account'                     => true,
		'agent.transfer_record'             => true,//代理转账记录
		'agent.merchant_setting'            => true,//代理商人绑定信息
		'agent.agent_message'               => true,//代理系统公告
		'agent.buy_record'                  => true,//代理进（上）分记录
		'agent.income_list'                 => true,//代理收入统计
		'agent.income_detail_list'          => true,//代理收入明细
		'agent.insert_transfer'             => true,//代理转账 (转账操作)
		// 'agent.update_settlement'       => true, //代理提现审核
		'agent.insert_settlement'           => true,//代理申请提现 (提交结算)
		'agent.insert_merchant_setting'     => true,//代理增加商人绑定
		'agent.update_merchant_setting'     => true,//代理修改商人绑定
		'agent.delete_merchant_setting'     => true,//代理删除商人绑定
		// 'agent.insert_agent_message'          => true,
		// 'agent.update_agent_message'          => true,
		// 'agent.delete_agent_message'          => true,
		'agent.insert_agent_account'        => true,// 添加代理
		'agent.update_agent_account'        => true,//修改代理账号
		'agent.update_agent_account_settle' => true,//  结算账户，结算密码

		// 'agent.delete_agent_account'    => true,
		// 'agent.recharge_setting'        => true,
		// 'agent.update_recharge_setting' => true,
		// 'agent.potato_robot_statics'    => true,
		// 'agent.user_win_total'          => true,
		// 'agent.user_charge_total'       => true,
		'operate.game_room_setting'           => true,

		'agent.ag_game_custom_setting'        => true,
		'agent.ag_game_info'                  => true,
		'agent.ag_insert_game'                => true,
		'agent.ag_delete_game'                => true,
        'operate.update_gm_account'           => true,//账户设置（修改自己账户的密码和昵称
        'agent.ag_get_player_transfer_record' => true,
        'agent.ag_get_agent_transfer_record' => true,
        'agent.ag_get_player_footmark' => true,
	],

];