<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_HTTP.pto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *增加配置的通用结构体//
 *
 * Generated from protobuf message <code>App.Proto.C2S_AGInsertSetting</code>
 */
class C2S_AGInsertSetting extends \Google\Protobuf\Internal\Message
{
    /**
     *需要新增的字段列表，eg:{[100，1]}//
     *
     * Generated from protobuf field <code>repeated string arrValues = 1;</code>
     */
    private $arrValues;
    /**
     *操作人,无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>string szAdmin = 3;</code>
     */
    private $szAdmin = '';
    /**
     *操作原因//
     *
     * Generated from protobuf field <code>string szMsg = 4;</code>
     */
    private $szMsg = '';
    /**
     *无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>string szBindID = 5;</code>
     */
    private $szBindID = '';
    /**
     *操作人,无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>uint32 szAdminLv = 6;</code>
     */
    private $szAdminLv = 0;
    /**
     *此次链接的token，5分钟内不活跃token自动失效
     *
     * Generated from protobuf field <code>string szToken = 7;</code>
     */
    private $szToken = '';

    public function __construct() {
	    \App\Proto\GPBMetadata\PbHTTP::initOnce();
	    parent::__construct();
    }

    /**
     *需要新增的字段列表，eg:{[100，1]}//
     *
     * Generated from protobuf field <code>repeated string arrValues = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArrValues()
    {
        return $this->arrValues;
    }

    /**
     *需要新增的字段列表，eg:{[100，1]}//
     *
     * Generated from protobuf field <code>repeated string arrValues = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArrValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->arrValues = $arr;

        return $this;
    }

    /**
     *操作人,无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>string szAdmin = 3;</code>
     * @return string
     */
    public function getSzAdmin()
    {
        return $this->szAdmin;
    }

    /**
     *操作人,无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>string szAdmin = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSzAdmin($var)
    {
        GPBUtil::checkString($var, True);
        $this->szAdmin = $var;

        return $this;
    }

    /**
     *操作原因//
     *
     * Generated from protobuf field <code>string szMsg = 4;</code>
     * @return string
     */
    public function getSzMsg()
    {
        return $this->szMsg;
    }

    /**
     *操作原因//
     *
     * Generated from protobuf field <code>string szMsg = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSzMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->szMsg = $var;

        return $this;
    }

    /**
     *无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>string szBindID = 5;</code>
     * @return string
     */
    public function getSzBindID()
    {
        return $this->szBindID;
    }

    /**
     *无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>string szBindID = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSzBindID($var)
    {
        GPBUtil::checkString($var, True);
        $this->szBindID = $var;

        return $this;
    }

    /**
     *操作人,无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>uint32 szAdminLv = 6;</code>
     * @return int
     */
    public function getSzAdminLv()
    {
        return $this->szAdminLv;
    }

    /**
     *操作人,无需赋值，服务器自动填写//
     *
     * Generated from protobuf field <code>uint32 szAdminLv = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSzAdminLv($var)
    {
        GPBUtil::checkUint32($var);
        $this->szAdminLv = $var;

        return $this;
    }

    /**
     *此次链接的token，5分钟内不活跃token自动失效
     *
     * Generated from protobuf field <code>string szToken = 7;</code>
     * @return string
     */
    public function getSzToken()
    {
        return $this->szToken;
    }

    /**
     *此次链接的token，5分钟内不活跃token自动失效
     *
     * Generated from protobuf field <code>string szToken = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSzToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->szToken = $var;

        return $this;
    }

}

