<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_HTTP.pto

namespace App\Proto;

/**
 * Protobuf enum <code>App\Proto\HttpMessageID</code>
 */
class httpMessageID
{
    /**
     *
     * Generated from protobuf enum <code>httpMessageID_unknown = 0;</code>
     */
    const httpMessageID_unknown = 0;
    /**
     *&#47;/增加游戏币//
     *
     * Generated from protobuf enum <code>HTTPAddGoldID = 9000;</code>
     */
    const HTTPAddGoldID = 9000;
    /**
     *&#47;/修改帐号状态//
     *
     * Generated from protobuf enum <code>HTTPModifyStateID = 9001;</code>
     */
    const HTTPModifyStateID = 9001;
    /**
     *&#47;/回复客服问题，客服反馈ID从数据库[Account_new].[dbo].[ServiceList]获取//
     *
     * Generated from protobuf enum <code>HTTPAnswerQuestionID = 9002;</code>
     */
    const HTTPAnswerQuestionID = 9002;
    /**
     *&#47;/兑换状态更新，兑换ID从数据库[Account_new].[dbo].[ExchangeList]获取//
     *
     * Generated from protobuf enum <code>HTTPExchangeStateID = 9003;</code>
     */
    const HTTPExchangeStateID = 9003;
    /**
     *&#47;/消息，消息ID从数据库[Configs].[dbo].[Messages]获取////
     *
     * Generated from protobuf enum <code>HTTPMessageID = 9004;</code>
     */
    const HTTPMessageID = 9004;
    /**
     *&#47;/游戏停服维护，维护期间已经开局的游戏可以继续，一局结束后自动离开房间，玩家则无法进入维护中的房间//
     *
     * Generated from protobuf enum <code>HTTPPreserveID = 9005;</code>
     */
    const HTTPPreserveID = 9005;
    /**
     *&#47;/房间奖池，税率设置，[Configs].[dbo].[RoomConfig]////
     *
     * Generated from protobuf enum <code>HTTPGameSettingID = 9006;</code>
     */
    const HTTPGameSettingID = 9006;
    /**
     *&#47;/修改帐号手机绑定信息////
     *
     * Generated from protobuf enum <code>HTTPModifyMobileID = 9007;</code>
     */
    const HTTPModifyMobileID = 9007;
    /**
     *&#47;/创建约战房间////
     *
     * Generated from protobuf enum <code>HTTPGameCreateID = 9008;</code>
     */
    const HTTPGameCreateID = 9008;
    /**
     *&#47;/修改帐号昵称//
     *
     * Generated from protobuf enum <code>HTTPModifyNickNameID = 9009;</code>
     */
    const HTTPModifyNickNameID = 9009;
    /**
     *&#47;/修改帐号支付宝//
     *
     * Generated from protobuf enum <code>HTTPModifyEmailID = 9010;</code>
     */
    const HTTPModifyEmailID = 9010;
    /**
     *&#47;/修改帐号密码,修改帐号银行密码//
     *
     * Generated from protobuf enum <code>HTTPModifyPasswordID = 9011;</code>
     */
    const HTTPModifyPasswordID = 9011;
    /**
     *&#47;/修改帐号代理//
     *
     * Generated from protobuf enum <code>HTTPModifyAgentID = 9012;</code>
     */
    const HTTPModifyAgentID = 9012;
    /**
     *&#47;/修改数据库指定表的字段//
     *
     * Generated from protobuf enum <code>HTTPUpdateSQLID = 9013;</code>
     */
    const HTTPUpdateSQLID = 9013;
    /**
     *&#47;/插入数据库指定表的字段//
     *
     * Generated from protobuf enum <code>HTTPInsertSQLID = 9014;</code>
     */
    const HTTPInsertSQLID = 9014;
    /**
     *&#47;/删除数据库指定表的内容//
     *
     * Generated from protobuf enum <code>HTTPDeleteSQLID = 9015;</code>
     */
    const HTTPDeleteSQLID = 9015;
    /**
     *&#47;/注册帐户//
     *
     * Generated from protobuf enum <code>HTTPRegistAccountID = 9016;</code>
     */
    const HTTPRegistAccountID = 9016;
    /**
     *&#47;/增加银行游戏币//
     *
     * Generated from protobuf enum <code>HTTPAddBankGoldID = 9017;</code>
     */
    const HTTPAddBankGoldID = 9017;
    /**
     *&#47;/游戏币转账//
     *
     * Generated from protobuf enum <code>HTTPTransferGoldID = 9018;</code>
     */
    const HTTPTransferGoldID = 9018;
}

