<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_HTTP.pto

namespace App\Proto;

/**
 * Protobuf enum <code>App\Proto\HttpErrorCode</code>
 */
class httpErrorCode
{
    /**
     *
     * Generated from protobuf enum <code>httpErrorCode_success = 0;</code>
     */
    const httpErrorCode_success = 0;
    /**
     *账号错误
     *
     * Generated from protobuf enum <code>httpErrorCode_Account = 1001;</code>
     */
    const httpErrorCode_Account = 1001;
    /**
     *游戏中，无法减扣游戏币
     *
     * Generated from protobuf enum <code>httpErrorCode_InGame = 1002;</code>
     */
    const httpErrorCode_InGame = 1002;
    /**
     *帐号余额不足
     *
     * Generated from protobuf enum <code>httpErrorCode_NoMoney = 1003;</code>
     */
    const httpErrorCode_NoMoney = 1003;
    /**
     *ID不存在
     *
     * Generated from protobuf enum <code>httpErrorCode_ID = 1004;</code>
     */
    const httpErrorCode_ID = 1004;
    /**
     *服务器繁忙
     *
     * Generated from protobuf enum <code>httpErrorCode_Busy = 1005;</code>
     */
    const httpErrorCode_Busy = 1005;
    /**
     *proto数据格式错误，无法解析
     *
     * Generated from protobuf enum <code>httpErrorCode_DataError = 1006;</code>
     */
    const httpErrorCode_DataError = 1006;
    /**
     *房间名字错误，无法解析
     *
     * Generated from protobuf enum <code>httpErrorCode_RoomError = 1007;</code>
     */
    const httpErrorCode_RoomError = 1007;
    /**
     *房间号已存在，无法创建
     *
     * Generated from protobuf enum <code>httpErrorCode_NumberError = 1008;</code>
     */
    const httpErrorCode_NumberError = 1008;
}

