<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_HTTP.pto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *通用的查询结果集结构//
 *
 * Generated from protobuf message <code>App.Proto.S2C_AGGetListRespond</code>
 */
class S2C_AGGetListRespond extends \Google\Protobuf\Internal\Message
{
    /**
     *返回的数据项eg:｛时间，注册人数，绑定人数，下注人数｝//
     *
     * Generated from protobuf field <code>.App.Proto.tyArrString arrTitles = 1;</code>
     */
    private $arrTitles = null;
    /**
     *返回的数据集eg：｛[｛2018-1-1，1，1，1｝，｛2018-1-2，2，2，2｝｛2018-1-3，3，3，3｝]｝//
     *
     * Generated from protobuf field <code>repeated .App.Proto.tyArrString arrDatas = 2;</code>
     */
    private $arrDatas;
    /**
     *总记录数//
     *
     * Generated from protobuf field <code>uint32 nTotal = 3;</code>
     */
    private $nTotal = 0;
    /**
     *返回的数据项的关键字段名字eg{["UserId","AgencyID","RecordTime","RegTime"]}:
     *
     * Generated from protobuf field <code>.App.Proto.tyArrString arrKeys = 4;</code>
     */
    private $arrKeys = null;

    public function __construct() {
	    \App\Proto\GPBMetadata\PbHTTP::initOnce();
        parent::__construct();
    }

    /**
     *返回的数据项eg:｛时间，注册人数，绑定人数，下注人数｝//
     *
     * Generated from protobuf field <code>.App.Proto.tyArrString arrTitles = 1;</code>
     * @return \App\Proto\tyArrString
     */
    public function getArrTitles()
    {
        return $this->arrTitles;
    }

    /**
     *返回的数据项eg:｛时间，注册人数，绑定人数，下注人数｝//
     *
     * Generated from protobuf field <code>.App.Proto.tyArrString arrTitles = 1;</code>
     * @param \App\Proto\tyArrString $var
     * @return $this
     */
    public function setArrTitles($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\tyArrString::class);
        $this->arrTitles = $var;

        return $this;
    }

    /**
     *返回的数据集eg：｛[｛2018-1-1，1，1，1｝，｛2018-1-2，2，2，2｝｛2018-1-3，3，3，3｝]｝//
     *
     * Generated from protobuf field <code>repeated .App.Proto.tyArrString arrDatas = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArrDatas()
    {
        return $this->arrDatas;
    }

    /**
     *返回的数据集eg：｛[｛2018-1-1，1，1，1｝，｛2018-1-2，2，2，2｝｛2018-1-3，3，3，3｝]｝//
     *
     * Generated from protobuf field <code>repeated .App.Proto.tyArrString arrDatas = 2;</code>
     * @param \App\Proto\tyArrString[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArrDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Proto\tyArrString::class);
        $this->arrDatas = $arr;

        return $this;
    }

    /**
     *总记录数//
     *
     * Generated from protobuf field <code>uint32 nTotal = 3;</code>
     * @return int
     */
    public function getNTotal()
    {
        return $this->nTotal;
    }

    /**
     *总记录数//
     *
     * Generated from protobuf field <code>uint32 nTotal = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->nTotal = $var;

        return $this;
    }

    /**
     *返回的数据项的关键字段名字eg{["UserId","AgencyID","RecordTime","RegTime"]}:
     *
     * Generated from protobuf field <code>.App.Proto.tyArrString arrKeys = 4;</code>
     * @return \App\Proto\tyArrString
     */
    public function getArrKeys()
    {
        return $this->arrKeys;
    }

    /**
     *返回的数据项的关键字段名字eg{["UserId","AgencyID","RecordTime","RegTime"]}:
     *
     * Generated from protobuf field <code>.App.Proto.tyArrString arrKeys = 4;</code>
     * @param \App\Proto\tyArrString $var
     * @return $this
     */
    public function setArrKeys($var)
    {
        GPBUtil::checkMessage($var, \App\Proto\tyArrString::class);
        $this->arrKeys = $var;

        return $this;
    }

}

