<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb_HTTP.pto

namespace App\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *字符串数据结构体
 *
 * Generated from protobuf message <code>App.Proto.tyArrString</code>
 */
class tyArrString extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47;/
     *
     * Generated from protobuf field <code>repeated string arrString = 1;</code>
     */
    private $arrString;

    public function __construct() {
	    \App\Proto\GPBMetadata\PbHTTP::initOnce();
	    parent::__construct();
    }

    /**
     *&#47;/
     *
     * Generated from protobuf field <code>repeated string arrString = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArrString()
    {
        return $this->arrString;
    }

    /**
     *&#47;/
     *
     * Generated from protobuf field <code>repeated string arrString = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArrString($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->arrString = $arr;

        return $this;
    }

}

